[project]
name = "http-bench-service"
version = "0.2.3"
description = "HTTP benchmark service"
readme = "README.md"
authors = [
    { name = "a.zaynagabdinov", email = "The.scorpion2006@yandex.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
bench = "http_bench_service:entrypoint"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
